language: python

python:
- "3.6.7"

install:
  - pip install -r requirements.txt
  - pip install coveralls

  env:
    - SECRET='4qQRAfszol6V4FW7Dyy4XNAtgZKrY6v1d'
    - APP_SETTINGS='testing'
script:
  - pytest --cov=./app

branches:
  only:
    - develop

after_success:
   - coverall
